version: "3"
services:
  sonarqube:
    image: sonarqube:9.4-community
    container_name: sonarqube
    restart: always
    environment:
      sonar.search.javaAdditionalOpts: "-Dnode.store.allow_mmap=false"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - sonar-network
    ports:
      - "9000:9000"

networks:
  sonar-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.2.0/24

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
